### ISSUE TITLE
Does not open iTerm2

### ISSUE THREAD

**Issue by scottbarrow** [mushanshitiancai/vscode-open-iterm2#1]
VSC Version 1.8.1 (1.8.1)
iTerm2 Build 3.0.12
Clicking Open iTerm2 here does nothing

**Comment by mushanshitiancai** [comment]
can you run `osascript` command in terminal successfully?

**Comment by scottbarrow** [comment]
no return when entering this on the command line within VSC
Scott

**Comment by mushanshitiancai** [comment]
You can do a more deail test. Create a file name `test.scpt`, and run `osascript test.scpt 'cd ~'` in iTerm2:

![image](https://cloud.githubusercontent.com/assets/4251771/22171461/a4c38bb6-dfc9-11e6-9b57-691870ffa335.png)

In normal case, iTerm2 would open a new tab and cd to you home directory.If fail you can tell me the error message.

**Comment by scottbarrow** [comment]
initially 
```
osascript test.scpt 'cd ~'   
                                            
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
```

after removing the file running `osascript test.scpt 'cd ~'` returned nothing

**Comment by mushanshitiancai** [comment]
It seems that there has some problem with your apple script execution command `osascript`.But I don't know what the problem is too😂

This extension depend on apple script to handle iTerm2.So you can do some search to fix `osascript test.scpt 'cd ~'`,and then this extension would work.

**Comment by scottbarrow** [comment]
I can create a generic script using Script Editor, and it runs successfully from iTerm2 directly

**Comment by mushanshitiancai** [comment]
sorry,  I forgot paste the code:

```
on run argv
	set prevDelimiter to AppleScript's text item delimiters
	
	set AppleScript's text item delimiters to " "
	set commands to argv as string
	set AppleScript's text item delimiters to prevDelimiter
	
	tell application "iTerm"
		activate
		if current window is missing value then
			create window with default profile
		else
			tell current window
				create tab with default profile
			end tell
		end if
		tell current session of current tab of current window
			write text commands
		end tell
	end tell
end run
```

The file you generic script from Script Editor is binary or plain text?

**Comment by scottbarrow** [comment]
test.scpt:259:265: script error: Expected “then”, etc. but found class name. (-2741)

**Comment by mushanshitiancai** [comment]
You may replace "iTerm" to "iTerm2", and then try again.
